### ISSUE TITLE
Got a messed up Deathsplosions from the longshot upgrade station

### ISSUE THREAD

**Issue by Traehgniw** [clementgallet/SWD2Randomizer#10]
![20180825155549_1](https://user-images.githubusercontent.com/42482668/44614810-6d211e00-a87f-11e8-8e2e-441db8309d91.jpg)

its name is apparently !MISSING LINE!! and i don't think it's supposed to do that. 

Casual seed C123456 and it's Deathsplosions, automatically on, taking away an upgrade cog. If I have 0 upgrade cogs going in, I end up with -1, which seems to be handled well in that nothing crashy happens, it doesn't roll over to the hypothetical cog cap, or do anything else strange.

**Comment by paroxysmal** [comment]
I've contacted the creator about this issue before myself. His answer was that since it comes from an upgrade station it is toggled on by default as every upgrade that comes from an upgrade station normally is toggled on by default. If you toggle it off you will get your cogs back. I am not sure if he intends to fix it, but its a minor issue same with the !missing line!! thing. Just look at your upgrade window if it says that its one of the 3 hidden blueprints, or the triple bomb if you get that message but none of the 3 hidden blueprints are on. You will just be down 3 cogs until you unlock the pressure bomb/grenade launcher

**Comment by clementgallet** [comment]
There's nothing much I can do about it. The randomizer is only messing with levels layout and is not modifying the game code.

**Comment by Traehgniw** [comment]
wait, you're making a randomizer mod, WITHOUT changing the game code?

**Comment by paroxysmal** [comment]
well core game i would imagine. i am not a skilled programmer, however, how i imagine it is he just modifies the item code for each upgrade location based on a number of seeds with a logic algorithm ensuring that there is no seed or path created that wouldn't be completable. It sounds complex but really i think the only thing that would need changed would be the item ids that each upgrade station gives out. which is possibly a very minor tweak overall.

**Comment by clementgallet** [comment]
I cannot fix the podium upgrade title yet, because the texts are compressed in ".z" files, and I couldn't find how to decompress them.

**Comment by clementgallet** [comment]
Fixed MISSING LINE message in 95a795280d591eb47ba40bb06d5992f30b4463c0
