### ISSUE TITLE
Suggestion: a return-to-town hotkey/force Portal of Pardon avaliablity after getting an upgrade?

### ISSUE THREAD

**Issue by Traehgniw** [clementgallet/SWD2Randomizer#7]
Right now, you need each upgrade to not just let you continue in the overworld, but also to get you out of the cave you are currently in, which reduces possible paths and possibly makes the rando generation code more complicated?  Since currently if you get into, way, Jackhammer cave, you need either Jackhammer or upgraded pressure bombs to escape. 

If, in the time between getting an upgrade and next leaving a cave by any method, you could teleport to town, it would mean that you wouldn't have to expect the player to be able to get out of the cave's upgrade station area. So you could open up more paths especially later in the game. It also would mean that you don't have to worry about softlocking yourself from not grinding for upgraded pressure bombs right out of Burster's.

**Comment by clementgallet** [comment]
I think the ability to teleport after getting an upgrade would weaken the interest of a randomizer. Yes, you are sometimes required to reset in a cave because you cannot escape, I think it's fine and part of the randomizer. The logic does not require you to fully upgrade pressure bombs to escape caves (except two or three caves in speedrun mode, but not much, and you probably have other possibilities).
